package lotteryapp;

/**
 * GUI for the Lotto Application
 *
 * @authors X15318921, X15420892, X15016650, X15758929
 */
import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;

public class GUI extends JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Gen1;
    private javax.swing.JTextField Gen2;
    private javax.swing.JTextField Gen3;
    private javax.swing.JTextField Gen4;
    private javax.swing.JTextField Gen5;
    private javax.swing.JLabel header;
    private javax.swing.JTextField Line1b1;
    private javax.swing.JTextField Line1b2;
    private javax.swing.JTextField Line1b3;
    private javax.swing.JTextField Line1b4;
    private javax.swing.JTextField Line1b5;
    private javax.swing.JTextField Line2b1;
    private javax.swing.JTextField Line2b2;
    private javax.swing.JTextField Line2b3;
    private javax.swing.JTextField Line2b4;
    private javax.swing.JTextField Line2b5;
    private javax.swing.JTextField Line3b1;
    private javax.swing.JTextField Line3b2;
    private javax.swing.JTextField Line3b3;
    private javax.swing.JTextField Line3b4;
    private javax.swing.JTextField Line3b5;
    private javax.swing.JLabel winningNumbLabel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel line1Label;
    private javax.swing.JLabel line2Label;
    private javax.swing.JLabel line3Label;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton lottoBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton plusOneBtn;
    private javax.swing.JButton qp1Btn;
    private javax.swing.JButton qp2Btn;
    private javax.swing.JButton qp3Btn;
    private javax.swing.JButton resetButton;
    private JColorChooser jColorChooser1;
    private javax.swing.JButton saveNumbersL1;
    private javax.swing.JButton saveNumbersL2;
    private javax.swing.JButton saveNumbersL3;
    private javax.swing.JButton fav1;

    // Stores user input numbers
    private int[] userLine1;
    private int[] userLine2;
    private int[] userLine3;

    // Stores winning numbers
    private int[] lottoNumbers;
    private int[] lottoPlusNumbers;
    private int[] lottoPlus1Numbers;

    //  Used to track if user has selected their lotto draw or not i.e. pressed button
    private boolean drawSelected = false;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        resetButton.show(false);
        saveNumbersL1.setEnabled(true);
        saveNumbersL1.show(true);
        saveNumbersL2.setEnabled(false);
        saveNumbersL2.show(false);
        saveNumbersL3.setEnabled(false);
        saveNumbersL3.show(false);
        fav1.setEnabled(true);
        fav1.show(true);

    }

//    public GUI() throws HeadlessException {
//    }
    public GUI(GraphicsConfiguration gc) {
        super(gc);
    }

    public GUI(String title) throws HeadlessException {
        super(title);
    }

    public GUI(String title, GraphicsConfiguration gc) {
        super(title, gc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        winningNumbLabel = new javax.swing.JLabel();
        saveNumbersL1 = new javax.swing.JButton();
        saveNumbersL2 = new javax.swing.JButton();
        saveNumbersL3 = new javax.swing.JButton();
        fav1 = new javax.swing.JButton();
        Line1b1 = new javax.swing.JTextField();
        Line1b2 = new javax.swing.JTextField();
        Line1b3 = new javax.swing.JTextField();
        Line1b4 = new javax.swing.JTextField();
        Line1b5 = new javax.swing.JTextField();
        Line2b1 = new javax.swing.JTextField();
        Line2b2 = new javax.swing.JTextField();
        Line2b3 = new javax.swing.JTextField();
        Line2b4 = new javax.swing.JTextField();
        Line2b5 = new javax.swing.JTextField();
        Line3b1 = new javax.swing.JTextField();
        Line3b2 = new javax.swing.JTextField();
        Line3b3 = new javax.swing.JTextField();
        Line3b4 = new javax.swing.JTextField();
        Line3b5 = new javax.swing.JTextField();
        Gen1 = new javax.swing.JTextField();
        Gen2 = new javax.swing.JTextField();
        Gen3 = new javax.swing.JTextField();
        Gen4 = new javax.swing.JTextField();
        Gen5 = new javax.swing.JTextField();
        line1Label = new javax.swing.JLabel();
        line2Label = new javax.swing.JLabel();
        line3Label = new javax.swing.JLabel();
        plusBtn = new javax.swing.JButton();
        plusOneBtn = new javax.swing.JButton();
        lottoBtn = new javax.swing.JButton();
        qp1Btn = new javax.swing.JButton();
        qp3Btn = new javax.swing.JButton();
        qp2Btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jButton5.setText("jButton5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/lotto header.png"))); // NOI18N
        jPanel1.add(header);
        header.setBounds(140, 10, 380, 60);

        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/resetBut.png"))); // NOI18N
        resetButton.setBorderPainted(false);
        resetButton.setContentAreaFilled(false);
        resetButton.setEnabled(false);
        resetButton.setFocusPainted(false);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton);
        resetButton.setBounds(380, 220, 100, 60);

        winningNumbLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/winnum.png"))); // NOI18N
        jPanel1.add(winningNumbLabel);
        winningNumbLabel.setBounds(70, 240, 340, 43);

        saveNumbersL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/Save.png"))); // NOI18N
        saveNumbersL1.setBorderPainted(false);
        saveNumbersL1.setContentAreaFilled(false);
        saveNumbersL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNumbersL1ActionPerformed(evt);
            }
        });
        jPanel1.add(saveNumbersL1);
        saveNumbersL1.setBounds(80, 80, 80, 50);

        saveNumbersL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/Save.png"))); // NOI18N
        saveNumbersL2.setBorderPainted(false);
        saveNumbersL2.setContentAreaFilled(false);
        jPanel1.add(saveNumbersL2);
        saveNumbersL2.setBounds(80, 130, 80, 50);

        saveNumbersL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/Save.png"))); // NOI18N
        saveNumbersL3.setBorderPainted(false);
        saveNumbersL3.setContentAreaFilled(false);
        jPanel1.add(saveNumbersL3);
        saveNumbersL3.setBounds(80, 190, 85, 40);

        fav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/luckyNumbers.png"))); // NOI18N
        fav1.setBorderPainted(false);
        fav1.setContentAreaFilled(false);
        fav1.setDefaultCapable(false);
        fav1.setFocusPainted(false);
        fav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fav1ActionPerformed(evt);
            }
        });
        jPanel1.add(fav1);
        fav1.setBounds(0, 20, 150, 46);

        Line1b1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line1b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line1b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line1b1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Line1b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1b1ActionPerformed(evt);
            }
        });
        jPanel1.add(Line1b1);
        Line1b1.setBounds(200, 90, 50, 30);

        Line1b2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line1b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line1b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line1b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1b2ActionPerformed(evt);
            }
        });
        jPanel1.add(Line1b2);
        Line1b2.setBounds(260, 90, 50, 30);

        Line1b3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line1b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line1b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line1b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1b3ActionPerformed(evt);
            }
        });
        jPanel1.add(Line1b3);
        Line1b3.setBounds(320, 90, 50, 30);

        Line1b4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line1b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line1b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line1b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1b4ActionPerformed(evt);
            }
        });
        jPanel1.add(Line1b4);
        Line1b4.setBounds(380, 90, 50, 30);

        Line1b5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line1b5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line1b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line1b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1b5ActionPerformed(evt);
            }
        });
        jPanel1.add(Line1b5);
        Line1b5.setBounds(440, 90, 50, 30);

        Line2b1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line2b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line2b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line2b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2b1ActionPerformed(evt);
            }
        });
        jPanel1.add(Line2b1);
        Line2b1.setBounds(200, 140, 50, 30);

        Line2b2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line2b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line2b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line2b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2b2ActionPerformed(evt);
            }
        });
        jPanel1.add(Line2b2);
        Line2b2.setBounds(260, 140, 50, 30);

        Line2b3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line2b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line2b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line2b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2b3ActionPerformed(evt);
            }
        });
        jPanel1.add(Line2b3);
        Line2b3.setBounds(320, 140, 50, 30);

        Line2b4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line2b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line2b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line2b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2b4ActionPerformed(evt);
            }
        });
        jPanel1.add(Line2b4);
        Line2b4.setBounds(380, 140, 50, 30);

        Line2b5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line2b5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line2b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line2b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2b5ActionPerformed(evt);
            }
        });
        jPanel1.add(Line2b5);
        Line2b5.setBounds(440, 140, 50, 30);

        Line3b1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line3b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line3b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line3b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line3b1ActionPerformed(evt);
            }
        });
        jPanel1.add(Line3b1);
        Line3b1.setBounds(200, 190, 50, 30);

        Line3b2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line3b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line3b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line3b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line3b2ActionPerformed(evt);
            }
        });
        jPanel1.add(Line3b2);
        Line3b2.setBounds(260, 190, 50, 30);

        Line3b3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line3b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line3b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line3b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line3b3ActionPerformed(evt);
            }
        });
        jPanel1.add(Line3b3);
        Line3b3.setBounds(320, 190, 50, 30);

        Line3b4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line3b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line3b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line3b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line3b4ActionPerformed(evt);
            }
        });
        jPanel1.add(Line3b4);
        Line3b4.setBounds(380, 190, 50, 30);

        Line3b5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Line3b5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Line3b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Line3b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line3b5ActionPerformed(evt);
            }
        });
        jPanel1.add(Line3b5);
        Line3b5.setBounds(440, 190, 50, 30);

        Gen1.setEditable(false);
        Gen1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Gen1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Gen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Gen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen1ActionPerformed(evt);
            }
        });
        jPanel1.add(Gen1);
        Gen1.setBounds(200, 290, 50, 30);

        Gen2.setEditable(false);
        Gen2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Gen2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Gen2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Gen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen2ActionPerformed(evt);
            }
        });
        jPanel1.add(Gen2);
        Gen2.setBounds(260, 290, 50, 30);

        Gen3.setEditable(false);
        Gen3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Gen3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Gen3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Gen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen3ActionPerformed(evt);
            }
        });
        jPanel1.add(Gen3);
        Gen3.setBounds(320, 290, 50, 30);

        Gen4.setEditable(false);
        Gen4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Gen4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Gen4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Gen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen4ActionPerformed(evt);
            }
        });
        jPanel1.add(Gen4);
        Gen4.setBounds(380, 290, 50, 30);

        Gen5.setEditable(false);
        Gen5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Gen5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Gen5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Gen5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen5ActionPerformed(evt);
            }
        });
        jPanel1.add(Gen5);
        Gen5.setBounds(440, 290, 50, 30);

        line1Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        line1Label.setForeground(new java.awt.Color(255, 255, 255));
        line1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/line1.png"))); // NOI18N
        jPanel1.add(line1Label);
        line1Label.setBounds(-20, 80, 120, 60);

        line2Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        line2Label.setForeground(new java.awt.Color(255, 255, 255));
        line2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/line2.png"))); // NOI18N
        jPanel1.add(line2Label);
        line2Label.setBounds(-20, 130, 120, 60);

        line3Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        line3Label.setForeground(new java.awt.Color(255, 255, 255));
        line3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/line3.png"))); // NOI18N
        jPanel1.add(line3Label);
        line3Label.setBounds(-20, 180, 110, 60);

        plusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/plus button.png"))); // NOI18N
        plusBtn.setBorderPainted(false);
        plusBtn.setContentAreaFilled(false);
        plusBtn.setFocusPainted(false);
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });
        jPanel1.add(plusBtn);
        plusBtn.setBounds(200, 330, 130, 60);

        plusOneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/plus1 button.png"))); // NOI18N
        plusOneBtn.setBorderPainted(false);
        plusOneBtn.setContentAreaFilled(false);
        plusOneBtn.setFocusPainted(false);
        plusOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusOneBtnActionPerformed(evt);
            }
        });
        jPanel1.add(plusOneBtn);
        plusOneBtn.setBounds(360, 330, 120, 60);

        lottoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/lotto button.png"))); // NOI18N
        lottoBtn.setBorderPainted(false);
        lottoBtn.setContentAreaFilled(false);
        lottoBtn.setFocusPainted(false);
        lottoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lottoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(lottoBtn);
        lottoBtn.setBounds(50, 330, 120, 60);

        qp1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/qpbutton.png"))); // NOI18N
        qp1Btn.setBorderPainted(false);
        qp1Btn.setContentAreaFilled(false);
        qp1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        qp1Btn.setFocusPainted(false);
        qp1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qp1BtnActionPerformed(evt);
            }
        });
        jPanel1.add(qp1Btn);
        qp1Btn.setBounds(150, 90, 60, 34);

        qp3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/qpbutton.png"))); // NOI18N
        qp3Btn.setBorderPainted(false);
        qp3Btn.setContentAreaFilled(false);
        qp3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qp3BtnActionPerformed(evt);
            }
        });
        jPanel1.add(qp3Btn);
        qp3Btn.setBounds(150, 190, 60, 40);

        qp2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/qpbutton.png"))); // NOI18N
        qp2Btn.setBorderPainted(false);
        qp2Btn.setContentAreaFilled(false);
        qp2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qp2BtnActionPerformed(evt);
            }
        });
        jPanel1.add(qp2Btn);
        qp2Btn.setBounds(150, 140, 60, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotteryapp/gui img/OrangeBackground.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 510, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Quick Pick Buttons
    private void qp1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qp1BtnActionPerformed
        // TODO add your handling code here:

        saveNumbersL1.setEnabled(true);
        saveNumbersL1.show(true);
        GenNumbers tmp = new GenNumbers();
        int[][] numbers = tmp.getArray(1);

        Line1b1.setText("" + numbers[0][0]);
        Line1b2.setText("" + numbers[0][1]);
        Line1b3.setText("" + numbers[0][2]);
        Line1b4.setText("" + numbers[0][3]);
        Line1b5.setText("" + numbers[0][4]);

        //  Disable the quickpick button after using it
        qp1Btn.setEnabled(false);
    }//GEN-LAST:event_qp1BtnActionPerformed

    private void qp3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qp3BtnActionPerformed

        //    saveNumbersL3.setEnabled(true);
        //    saveNumbersL3.show(true);
        GenNumbers tmp = new GenNumbers();
        int[][] numbers = tmp.getArray(1);

        Line3b1.setText("" + numbers[0][0]);
        Line3b2.setText("" + numbers[0][1]);
        Line3b3.setText("" + numbers[0][2]);
        Line3b4.setText("" + numbers[0][3]);
        Line3b5.setText("" + numbers[0][4]);

        qp3Btn.setEnabled(false);
    }//GEN-LAST:event_qp3BtnActionPerformed

    private void qp2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qp2BtnActionPerformed
//        saveNumbersL2.setEnabled(true);
        //       saveNumbersL2.show(true);

        GenNumbers tmp = new GenNumbers();
        int[][] numbers = tmp.getArray(1);

        Line2b1.setText("" + numbers[0][0]);
        Line2b2.setText("" + numbers[0][1]);
        Line2b3.setText("" + numbers[0][2]);
        Line2b4.setText("" + numbers[0][3]);
        Line2b5.setText("" + numbers[0][4]);

        qp2Btn.setEnabled(false);
    }//GEN-LAST:event_qp2BtnActionPerformed

    //Line One / User Numbers
    private void Line1b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1b1ActionPerformed

    private void Line1b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1b2ActionPerformed

    private void Line1b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1b3ActionPerformed

    private void Line1b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1b4ActionPerformed

    private void Line1b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1b5ActionPerformed

    // Line 2 / User Numbers
    private void Line2b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2b1ActionPerformed

    private void Line2b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2b2ActionPerformed

    private void Line2b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2b3ActionPerformed

    private void Line2b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2b4ActionPerformed

    private void Line2b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2b5ActionPerformed

    // Line 3 / User Numbers
    private void Line3b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line3b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line3b1ActionPerformed

    private void Line3b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line3b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line3b2ActionPerformed

    private void Line3b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line3b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line3b3ActionPerformed

    private void Line3b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line3b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line3b4ActionPerformed

    private void Line3b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line3b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line3b5ActionPerformed

    // Winning Numbers
    private void Gen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen1ActionPerformed

    }//GEN-LAST:event_Gen1ActionPerformed

    private void Gen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gen2ActionPerformed

    private void Gen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gen3ActionPerformed

    private void Gen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gen4ActionPerformed

    private void Gen5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gen5ActionPerformed

    //Lotto Draw Buttons
    private void lottoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lottoBtnActionPerformed
        resetInputColor();

        //  Checks if any draw button has been pressed
        if (drawSelected == false) {
            drawSelected = true;
            resetButton.setEnabled(true);
            resetButton.show(true);

            //  Disable the LottoPlus and LottoPlusOne buttons
            plusBtn.setEnabled(false);
            plusOneBtn.setEnabled(false);

            //  Generate numbers for Lotto
            GenNumbers gen = new GenNumbers();
            int[][] nums = gen.getArray(1);
            lottoNumbers = nums[0];
        }

        //  Check matching numbers
        //  will be length 0 if there is missing input
        userLine1 = getUserLine1();
        for (int i = 0; i < lottoNumbers.length; i++) {
            //  Won't loop if there was blank input, because userLine1 will be length 0 array (empty)
            for (int j = 0; j < userLine1.length; j++) {
                if (lottoNumbers[i] == userLine1[j]) {
                    if (j == 0) {
                        Line1b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line1b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line1b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line1b4.setBackground(Color.GREEN);
                    } else {
                        Line1b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        userLine2 = getUserLine2();
        for (int i = 0; i < lottoNumbers.length; i++) {
            for (int j = 0; j < userLine2.length; j++) {
                if (lottoNumbers[i] == userLine2[j]) {
                    if (j == 0) {
                        Line2b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line2b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line2b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line2b4.setBackground(Color.GREEN);
                    } else {
                        Line2b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        userLine3 = getUserLine3();
        for (int i = 0; i < lottoNumbers.length; i++) {
            for (int j = 0; j < userLine3.length; j++) {
                if (lottoNumbers[i] == userLine3[j]) {
                    if (j == 0) {
                        Line3b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line3b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line3b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line3b4.setBackground(Color.GREEN);
                    } else {
                        Line3b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        //  Populating winning number textfields
        Gen1.setText("" + lottoNumbers[0]);
        Gen2.setText("" + lottoNumbers[1]);
        Gen3.setText("" + lottoNumbers[2]);
        Gen4.setText("" + lottoNumbers[3]);
        Gen5.setText("" + lottoNumbers[4]);

//        lottoBtn.setEnabled(false);

    }//GEN-LAST:event_lottoBtnActionPerformed
    // Lotto Plus Button 
    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        resetInputColor();
        if (drawSelected == false) {
            drawSelected = true;
            resetButton.setEnabled(true);
            resetButton.show(true);

            //  Disable the LottoPlusOne button
            plusOneBtn.setEnabled(false);

            //  Generate numbers for Lotto, and LottoPlus
            GenNumbers gen = new GenNumbers();
            int[][] nums = gen.getArray(2);
            lottoNumbers = nums[0];
            lottoPlusNumbers = nums[1];
        }

        //  Check matching numbers
        userLine1 = getUserLine1();
        for (int i = 0; i < lottoPlusNumbers.length; i++) {
            for (int j = 0; j < userLine1.length; j++) {
                if (lottoPlusNumbers[i] == userLine1[j]) {
                    if (j == 0) {
                        Line1b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line1b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line1b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line1b4.setBackground(Color.GREEN);
                    } else {
                        Line1b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        userLine2 = getUserLine2();
        for (int i = 0; i < lottoPlusNumbers.length; i++) {
            for (int j = 0; j < userLine2.length; j++) {
                if (lottoPlusNumbers[i] == userLine2[j]) {
                    if (j == 0) {
                        Line2b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line2b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line2b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line2b4.setBackground(Color.GREEN);
                    } else {
                        Line2b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        userLine3 = getUserLine3();
        for (int i = 0; i < lottoPlusNumbers.length; i++) {
            for (int j = 0; j < userLine3.length; j++) {
                if (lottoPlusNumbers[i] == userLine3[j]) {
                    if (j == 0) {
                        Line3b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line3b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line3b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line3b4.setBackground(Color.GREEN);
                    } else {
                        Line3b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        Gen1.setText("" + lottoPlusNumbers[0]);
        Gen2.setText("" + lottoPlusNumbers[1]);
        Gen3.setText("" + lottoPlusNumbers[2]);
        Gen4.setText("" + lottoPlusNumbers[3]);
        Gen5.setText("" + lottoPlusNumbers[4]);
    }//GEN-LAST:event_plusBtnActionPerformed

    private void plusOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusOneBtnActionPerformed
        resetInputColor();
        if (drawSelected == false) {
            drawSelected = true;
            resetButton.setEnabled(true);
            resetButton.show(true);

            //  Generate numbers for Lotto, LottoPlus, and LottPlusOne
            GenNumbers gen = new GenNumbers();
            int[][] nums = gen.getArray(3);
            lottoNumbers = nums[0];
            lottoPlusNumbers = nums[1];
            lottoPlus1Numbers = nums[2];
        }

        //  Check matching numbers
        userLine1 = getUserLine1();
        for (int i = 0; i < lottoPlus1Numbers.length; i++) {
            for (int j = 0; j < userLine1.length; j++) {
                if (lottoPlus1Numbers[i] == userLine1[j]) {
                    if (j == 0) {
                        Line1b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line1b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line1b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line1b4.setBackground(Color.GREEN);
                    } else {
                        Line1b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        userLine2 = getUserLine2();
        for (int i = 0; i < lottoPlus1Numbers.length; i++) {
            for (int j = 0; j < userLine2.length; j++) {
                if (lottoPlus1Numbers[i] == userLine2[j]) {
                    if (j == 0) {
                        Line2b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line2b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line2b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line2b4.setBackground(Color.GREEN);
                    } else {
                        Line2b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        userLine3 = getUserLine3();
        for (int i = 0; i < lottoPlus1Numbers.length; i++) {
            for (int j = 0; j < userLine3.length; j++) {
                if (lottoPlus1Numbers[i] == userLine3[j]) {
                    if (j == 0) {
                        Line3b1.setBackground(Color.GREEN);
                    } else if (j == 1) {
                        Line3b2.setBackground(Color.GREEN);
                    } else if (j == 2) {
                        Line3b3.setBackground(Color.GREEN);
                    } else if (j == 3) {
                        Line3b4.setBackground(Color.GREEN);
                    } else {
                        Line3b5.setBackground(Color.GREEN);
                    }
                }
            }
        }

        Gen1.setText("" + lottoPlus1Numbers[0]);
        Gen2.setText("" + lottoPlus1Numbers[1]);
        Gen3.setText("" + lottoPlus1Numbers[2]);
        Gen4.setText("" + lottoPlus1Numbers[3]);
        Gen5.setText("" + lottoPlus1Numbers[4]);
    }//GEN-LAST:event_plusOneBtnActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        drawSelected = false;
        Line1b1.setText("");
        Line1b2.setText("");
        Line1b3.setText("");
        Line1b4.setText("");
        Line1b5.setText("");
        Line2b1.setText("");
        Line2b2.setText("");
        Line2b3.setText("");
        Line2b4.setText("");
        Line2b5.setText("");
        Line3b1.setText("");
        Line3b2.setText("");
        Line3b3.setText("");
        Line3b4.setText("");
        Line3b5.setText("");
        Gen1.setText("");
        Gen2.setText("");
        Gen3.setText("");
        Gen4.setText("");
        Gen5.setText("");
        Line1b1.setBackground(Color.WHITE);
        Line1b2.setBackground(Color.WHITE);
        Line1b3.setBackground(Color.WHITE);
        Line1b4.setBackground(Color.WHITE);
        Line1b5.setBackground(Color.WHITE);
        Line2b1.setBackground(Color.WHITE);
        Line2b2.setBackground(Color.WHITE);
        Line2b3.setBackground(Color.WHITE);
        Line2b4.setBackground(Color.WHITE);
        Line2b5.setBackground(Color.WHITE);
        Line3b1.setBackground(Color.WHITE);
        Line3b2.setBackground(Color.WHITE);
        Line3b3.setBackground(Color.WHITE);
        Line3b4.setBackground(Color.WHITE);
        Line3b5.setBackground(Color.WHITE);
        qp1Btn.setEnabled(true);
        qp2Btn.setEnabled(true);
        qp3Btn.setEnabled(true);
        lottoBtn.setEnabled(true);
        plusBtn.setEnabled(true);
        plusOneBtn.setEnabled(true);
        resetButton.setEnabled(false);
        resetButton.show(false);


    }//GEN-LAST:event_resetButtonActionPerformed

    private void saveNumbersL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNumbersL1ActionPerformed
//        fav1.setEnabled(false);
//        fav1.show(false);

        File outFile;  //1.Create an instance of File class
        FileWriter fw;  //2.Create Charachter Stream
        BufferedWriter bw;//3.Create a Buffered Stream

        int[] saveNumbers1 = getUserLine1();

        try {
            outFile = new File("savedNumbers.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            for (int i = 0; i < saveNumbers1.length; i++) {
                if (i == 0) {
                    bw.write("" + saveNumbers1[i]); //Write array members to the file without "," at the start
                } else {
                    bw.write("," + saveNumbers1[i]);//Add "," in between numbers for the split method
                }

                //  System.out.println(saveNumbers1[i]);
            }
            bw.newLine();       //Bring to the new line
            bw.close();
            JOptionPane.showMessageDialog(null, "Your Numbers Have Been Saved, God Bless You");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }


    }//GEN-LAST:event_saveNumbersL1ActionPerformed

    private void fav1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fav1ActionPerformed
        // TODO add your handling code here:
        
        File inFile;
        FileReader fr;
        BufferedReader br;
        
        String userLine;

        try {
            inFile = new File("savedNumbers.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            userLine = br.readLine();
            while (userLine != null) {
                userLine = br.readLine();  //Use the last line in the text file as Lucky Numbers
                if (userLine != null) {
                    String[] numbers = userLine.split(",");  //Split method used to seperate numbers 

                    Line1b1.setText(numbers[0]);
                    Line1b2.setText(numbers[1]);
                    Line1b3.setText(numbers[2]);
                    Line1b4.setText(numbers[3]);
                    Line1b5.setText(numbers[4]);
                }
            }

        } catch (IOException e) {
            System.out.print(e);
        }

    }//GEN-LAST:event_fav1ActionPerformed

    //  Sets input backgrounds back to white
    private void resetInputColor() {
        Line1b1.setBackground(Color.WHITE);
        Line1b2.setBackground(Color.WHITE);
        Line1b3.setBackground(Color.WHITE);
        Line1b4.setBackground(Color.WHITE);
        Line1b5.setBackground(Color.WHITE);

        Line2b1.setBackground(Color.WHITE);
        Line2b2.setBackground(Color.WHITE);
        Line2b3.setBackground(Color.WHITE);
        Line2b4.setBackground(Color.WHITE);
        Line2b5.setBackground(Color.WHITE);

        Line3b1.setBackground(Color.WHITE);
        Line3b2.setBackground(Color.WHITE);
        Line3b3.setBackground(Color.WHITE);
        Line3b4.setBackground(Color.WHITE);
        Line3b5.setBackground(Color.WHITE);
    }

    //  Return int array of values from the textfields of line 1
    private int[] getUserLine1() {
        //  Get the values from the input boxes
        String input1 = Line1b1.getText();
        String input2 = Line1b2.getText();
        String input3 = Line1b3.getText();
        String input4 = Line1b4.getText();
        String input5 = Line1b5.getText();

        //  Make sure none are empty
        if (input1.isEmpty() || input2.isEmpty() || input3.isEmpty() || input4.isEmpty() || input5.isEmpty()) {
            //  If there is an empty box, return an empty array
            //  This is because an empty string will crash Integer.parseInt
            //  and the array size is 0 so it doesn't loop through when checking
            //  for matching numbers.
            return new int[0];
        }

        int num1 = Integer.parseInt(input1);
        int num2 = Integer.parseInt(input2);
        int num3 = Integer.parseInt(input3);
        int num4 = Integer.parseInt(input4);
        int num5 = Integer.parseInt(input5);
        int[] line1 = {num1, num2, num3, num4, num5};
        return line1;
    }

    //  Return int array of values from the textfields of line 2
    private int[] getUserLine2() {
        String input1 = Line2b1.getText();
        String input2 = Line2b2.getText();
        String input3 = Line2b3.getText();
        String input4 = Line2b4.getText();
        String input5 = Line2b4.getText();

        if (input1.isEmpty() || input2.isEmpty() || input3.isEmpty() || input4.isEmpty() || input5.isEmpty()) {
            return new int[0];
        }

        int num1 = Integer.parseInt(Line2b1.getText());
        int num2 = Integer.parseInt(Line2b2.getText());
        int num3 = Integer.parseInt(Line2b3.getText());
        int num4 = Integer.parseInt(Line2b4.getText());
        int num5 = Integer.parseInt(Line2b5.getText());
        int[] line2 = {num1, num2, num3, num4, num5};
        return line2;
    }

    //  Return int array of values from the textfields of line 3
    private int[] getUserLine3() {
        String input1 = Line3b1.getText();
        String input2 = Line3b2.getText();
        String input3 = Line3b3.getText();
        String input4 = Line3b4.getText();
        String input5 = Line3b4.getText();

        if (input1.isEmpty() || input2.isEmpty() || input3.isEmpty() || input4.isEmpty() || input5.isEmpty()) {
            return new int[0];
        }

        int num1 = Integer.parseInt(Line3b1.getText());
        int num2 = Integer.parseInt(Line3b2.getText());
        int num3 = Integer.parseInt(Line3b3.getText());
        int num4 = Integer.parseInt(Line3b4.getText());
        int num5 = Integer.parseInt(Line3b5.getText());
        int[] line3 = {num1, num2, num3, num4, num5};
        return line3;
    }

}

/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Gen1;
    private javax.swing.JTextField Gen2;
    private javax.swing.JTextField Gen3;
    private javax.swing.JTextField Gen4;
    private javax.swing.JTextField Gen5;
    private javax.swing.JTextField Line1b1;
    private javax.swing.JTextField Line1b2;
    private javax.swing.JTextField Line1b3;
    private javax.swing.JTextField Line1b4;
    private javax.swing.JTextField Line1b5;
    private javax.swing.JTextField Line2b1;
    private javax.swing.JTextField Line2b2;
    private javax.swing.JTextField Line2b3;
    private javax.swing.JTextField Line2b4;
    private javax.swing.JTextField Line2b5;
    private javax.swing.JTextField Line3b1;
    private javax.swing.JTextField Line3b2;
    private javax.swing.JTextField Line3b3;
    private javax.swing.JTextField Line3b4;
    private javax.swing.JTextField Line3b5;
    private javax.swing.JButton fav1;
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton5;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel line1Label;
    private javax.swing.JLabel line2Label;
    private javax.swing.JLabel line3Label;
    private javax.swing.JButton lottoBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton plusOneBtn;
    private javax.swing.JButton qp1Btn;
    private javax.swing.JButton qp2Btn;
    private javax.swing.JButton qp3Btn;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveNumbersL1;
    private javax.swing.JButton saveNumbersL2;
    private javax.swing.JButton saveNumbersL3;
    private javax.swing.JLabel winningNumbLabel;
    // End of variables declaration//GEN-END:variables
*/
